import pandas as pd
import requests
import datetime
import hashlib
import json

# 1. Configuration
# Replace with your actual n8n Webhook URL
WEBHOOK_URL = "https://robertofernandezmartinez.app.n8n.cloud/webhook-test/vessel-alert" 

def generate_prediction_id(vessel_id, timestamp):
    """Generates a unique ID to prevent duplicates in Google Sheets (Upsert logic)"""
    unique_str = f"{vessel_id}_{timestamp}"
    return hashlib.sha256(unique_str.encode()).hexdigest()[:12]

def send_to_n8n():
    """Processes predictions and triggers the n8n automation workflow"""
    try:
        # Load the predictions generated by the ML model
        df = pd.read_csv('05_Outputs/predictions.csv')
    except FileNotFoundError:
        print("❌ Error: 'predictions.csv' not found. Please run the ML model first.")
        return

    # In Phase 2, we send the top 5 highest-risk vessels
    # n8n will decide whether to trigger an AI alert or just log the data
    top_vessels = df.sort_values(by='delay_risk_score', ascending=False).head(5)

    print(f"🚀 Starting notification process for {len(top_vessels)} vessels...")

    for _, row in top_vessels.iterrows():
        # Prepare clean, standardized ISO timestamp
        now_iso = datetime.datetime.utcnow().isoformat() + "Z"
        vessel_id = int(row['vessel_id'])
        risk_score = round(float(row['delay_risk_score']), 2)
        
        # Determine risk level for n8n conditional logic
        risk_level = "Critical" if risk_score > 0.8 else "Elevated"
        
        payload = {
            "prediction_id": generate_prediction_id(vessel_id, now_iso),
            "timestamp_prediction": now_iso,
            "vessel_id": vessel_id,
            "delay_minutes": int(row['predicted_delay_minutes']),
            "risk_score": risk_score,
            "risk_level": risk_level,
            "status": "Pending Review",
            "recommended_action": "Reassign docking slot" if risk_score > 0.8 else "Monitor status"
        }

        # Send data to the n8n Webhook
        try:
            response = requests.post(WEBHOOK_URL, json=payload, timeout=10)
            if response.status_code == 200:
                print(f"✅ Vessel {vessel_id} | Risk: {risk_score} | Sent successfully (ID: {payload['prediction_id']})")
            else:
                print(f"⚠️ Warning: Vessel {vessel_id} failed with status {response.status_code}")
        except requests.exceptions.RequestException as e:
            print(f"❌ Connection error for Vessel {vessel_id}: {e}")

if __name__ == "__main__":
    send_to_n8n()