import pandas as pd
import requests
import os

# n8n Test URL here
N8N_WEBHOOK_URL = "https://robertofernandezmartinez.app.n8n.cloud/webhook-test/vessel-alert"

# Path to the predictions file generated by execution.py
INPUT_CSV = '05_Outputs/predictions.csv'

def send_vessel_alerts():
    """
    Reads the prediction results and sends critical alerts to n8n for AI processing.
    """
    # Check if the predictions file exists
    if not os.path.exists(INPUT_CSV):
        print(f"✘ Error: {INPUT_CSV} not found. Please run execution.py first.")
        return

    # Load prediction results
    try:
        df = pd.read_csv(INPUT_CSV)
    except Exception as e:
        print(f"✘ Error reading CSV: {e}")
        return

    # Filter only CRITICAL risk level vessels
    critical_vessels = df[df['risk_level'] == 'CRITICAL']

    if critical_vessels.empty:
        print("✔ No critical risks detected in this batch.")
        return

    print(f"🚢 Found {len(critical_vessels)} critical vessels.")
    print(f"📡 Sending the top 3 alerts to n8n for AI Agent processing...")

    # Send the first 3 for the initial test to avoid flooding
    for _, row in critical_vessels.head(3).iterrows():
        payload = {
            "vessel_id": str(row['vessel_id']),
            "risk_score": float(row['risk_score']),
            "risk_level": row['risk_level'],
            "recommended_action": row['recommended_action'],
            "project": "SmartPort-AI-Agent"
        }
        
        try:
            # Send data to n8n Webhook
            response = requests.post(N8N_WEBHOOK_URL, json=payload)
            
            if response.status_code == 200:
                print(f"✅ SUCCESS: Data for vessel {row['vessel_id']} sent to n8n.")
            else:
                print(f"⚠ Error {response.status_code} sending vessel {row['vessel_id']}")
                
        except Exception as e:
            print(f"✘ Connection error with n8n: {e}")

if __name__ == "__main__":
    send_vessel_alerts()